### ISSUE TITLE
RFE: Provide information in README.md on suggested MPI packages to install

### ISSUE THREAD

**Issue by ijjorama** [DiamondLightSource/DosNa#5]
Hi,
I'm trying to install DosNa again. I ran a test:
```
sh run_tests.sh --backend ram --engine cpu
Unittest manual mode: --backend ram --engine cpu
========================================
Running tests on connection
========================================
2018-06-07 13:26:49,597 - __main__ - INFO - ConnectionTest: ram, cpu, {'name': 'test-dosna'}
INFO:__main__:ConnectionTest: ram, cpu, {'name': 'test-dosna'}
test_config (__main__.ConnectionTest) ... ok
test_connection (__main__.ConnectionTest) ... ok

----------------------------------------------------------------------
Ran 2 tests in 0.002s

OK
========================================
Running tests on dataset
========================================

...
...
----------------------------------------------------------------------
Ran 10 tests in 0.709s

OK
========================================
Running tests on dataset_mpi
========================================
Traceback (most recent call last):
  File "/home/ijj87/virtualenv/DosNa/DosNa/dosna/tests/test_dataset_mpi.py", line 11, in <module>
    from dosna.util.mpi import mpi_barrier
  File "build/bdist.linux-x86_64/egg/dosna/util/mpi.py", line 9, in <module>
ImportError: No module named mpi4py

```
Can you advise which RPMs and Python pip packages I should install to provide mpi4py?

Thanks,
Ian.

**Comment by EmilioPeJu** [comment]
I believe you could use: pip install mpi4py
if you are installing from scratch you could use the mpi extra feature by typing: pip install DosNa[mpi]
(please keep in mind that mpi4py uses openmpi dynamic libraries)
